added setup instructions for sudo-less RPi usage
adafruit/Adafruit_CircuitPython_NeoPixel pull request #146
Opened 2022-12-11 00:56 UTC by Kasperror

Resolved the problem when using the SPI MOSI (GPIO 10) would result in unexpected behaviour when sending signals for a long periods. Turns out that Serial interface/ Serial port hardware has to be enabled otherwise the communication on SPI was being cut after few seconds.

2022-12-12 19:19 UTC, tannewt requested changes
I think this should make pylint happy. Thanks for adding the usage example!

2022-12-12 19:19 UTC, tannewt commented on README.rst
> +2. Reboot the Pi to apply the changes - the hardware setup takes place during boot.
```suggestion
2. Reboot the Pi to apply the changes - the hardware setup takes place during boot.
```

2022-12-12 19:19 UTC, tannewt commented on README.rst
> +
```suggestion

```

2022-12-13 16:53 UTC, tannewt commented on README.rst
> +
Can you do it as a `.. code-block::` and then omit the spaces? I don't have any more CI info. My next step would be to run pre-commit locally to see what it changes. (Some other libraries do print out a diff I think. NeoPixel may not have it.)

2022-12-23 16:01 UTC, powerjungle commented
I just tested this and it works, but there's a problem.

My setup is this: https://learn.adafruit.com/assets/64121
Except I connected to GPIO10, as explained in the commit. I enabled SPI and Serial port, using raspi-config, rebooted and when I tried to run this script without using sudo:
```
import board
import neopixel
pixels = neopixel.NeoPixel(board.D10, 50, auto_write=False, pixel_order=neopixel.RGB)
pixels.fill((255, 255, 255))
pixels.show()
```
The code ran, but all LEDs, light up as orange, not white. When I ran it earlier using sudo and GPIO18 it was all fine.

2022-12-24 13:25 UTC, powerjungle commented
When I tried this method it works, but I have a weird issue, which I'm not sure if it's from my setup. The moment I hooked up to the GPIO10 pin and started using it, my data seems corrupted. The LEDs light up with the wrong colors and some are flashing when they shouldn't be. I'm using a big power supply which should be able to handle 8 amps, which should be more then enough for my 50 LEDs. I tested on a lower brightness and same thing. It's always consistently the same wrong colors too. For example when I run this:
```
import board
import neopixel
pixels = neopixel.NeoPixel(board.D10, 50)
pixels.fill((255, 255, 255))
```
They all light up as orange instead of white. When, I try turning them on one by one to blue, they first turn pink and then blue.

This is my setup: https://learn.adafruit.com/assets/64121

I think it might be some timing issue, because when I set `auto_write=False` and then add a delay between fill() and show() all LEDs turn off as they should, without the delay, the first one remains on light up as red, even though I didn't set it to red.

As far as I remember, the issue happened, the moment I switched to the new pin and started using this method, when I tried the old method using root and GPIO18, the issue persisted. That's what made me think it's something from my setup, but I can't think of why it would be working normally before and now just crap out randomly. Maybe I messed something up in the hardware, hope I didn't kill my GPIO lol.

I tried setting `spidev.bufsiz=32768` in `/boot/cmdline.txt` just in case, but no difference. I got this info from here: https://pypi.org/project/rpi-ws281x

2022-12-24 14:16 UTC, dhalbert commented
@powerjungle Did you ever get the correct colors? Do you have RGBW NeoPixels instead of RGB ones? Do you have the part number for the strip you have?

2022-12-24 14:21 UTC, powerjungle commented
@dhalbert yeah like I said:
> but I can't think of why it would be working normally before and now just crap out randomly

They were working normally before that. I changed between RGBW and RGB when using the module, but it didn't make a difference.

These are the ones I have: https://www.amazon.de/dp/B06XD72LYM?psc=1&ref=ppx_yo2ov_dt_b_product_details

It might be that they're just defective or that I fried something, but it was just a weird coincidence with switching to this method, so I wanted to mention just in case. There might be some configuration that is be needed on the raspberry or the python module, no idea. Only way to be sure is to get new lights, but right now I can't, so I'm throwing this out there in case anyone has ideas what the cause might be, if it's something obvious that I'm missing.

2023-01-09 23:27 UTC, Kasperror commented
> 

Make sure you have a common GND for LED's and RPi board?

2023-02-24 23:05 UTC, FoamyGuy commented
I cloned this locally and ran pre-commit to get the formatting fixed. I don't have permission to commit to this branch in the PR though so I cannot update it here. 

This link should go to a comparison that shows the difference needed to make the formatting check happy. https://github.com/Kasperror/Adafruit_CircuitPython_NeoPixel/compare/patch-1...FoamyGuy:Adafruit_CircuitPython_NeoPixel:foamyguy-kasperror-patch-1

@Kasperror if you make that change in your branch and push a new commit with it then it should update here and pass the actions I believe.

I'm also going to open a new PR with this change made on my own fork of your branch just in case you don't have time to get back to this so that we can still move it forward in the Adafruit fork.

2023-02-25 03:49 UTC, Kasperror reviewed
all changes were fixed

2023-02-25 03:54 UTC, Kasperror commented
Thanks to @FoamyGuy 's research the code finally managed to pass the tests. If you may, please merge the changes so others can use the led rings without `sudo` without adding another "issue"

2023-02-25 15:14 UTC, FoamyGuy approved these changes
Looks good to me. 

Tested successfully on Raspberry Pi 3 B+. Blinka and neopixel library both installed without sudo and then was able to successfully run the example script (modified for pin 10) successfully also without sudo.

2023-03-09 18:03 UTC, tannewt approved these changes
Yup! Thanks for the ping.

2023-03-09 18:03 UTC, merged